#!/usr/bin/env bash

set -euxo pipefail

if [[ $# -gt 0 ]]; then
  echo "
  Usage: ${0##*/}
  Builds and installs KnightCode onto your system into ~/.local, making it available as ~/.local/bin/knightcode-ide.

  Before running this you should ensure you have all the build dependencies installed with `./script/linux`,
  and set KNIGHTCODE_ENGINE_DIR to the directory 'bun run build:engine' writes.
  "
  exit 1
fi
export ZED_CHANNEL=$(<crates/zed/RELEASE_CHANNEL)
export ZED_UPDATE_EXPLANATION="You need to fetch and rebuild KnightCode in $(pwd)"
script/bundle-linux

arch="$(uname -m)"
commit=$(git rev-parse HEAD | cut -c 1-7)
archive="knightcode-linux-${arch}.tar.gz"
export ZED_BUNDLE_PATH="${CARGO_TARGET_DIR:-target}/release/${archive}"
script/install.sh
